config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/camera', to: 'pages#camera'
  resources :photos, only: [:create, :destroy]

  get '/googleApi', to: 'photos#googleApi'



  resources :users, only: [] do
    resources :photos, only: [] do
    resources :comments, only: [:new, :create]
  end
    resources :events, only: [] do
      resources :event_guests, only: [:create]
      resources :likes, only: [:create, :new]
    end
  end

  resources :events do
    collection do
      get 'search', to: 'events#search'
      get 'nearby', to: 'events#nearby'
    end
    resources :photos, only: [:create, :show, :destroy] do
      get '/like', to: 'likes#like'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-shary ">

  <!-- event -->
  <div class="center">
  <%= link_to events_path, class: "event" do %>
  <i class="far fa-calendar-alt fa-lg"></i>
  <% end %>
  <p>Events</p>
  </div>

  <!--  create -->
  <div class="center">
  <%= link_to new_event_path, class: "create" do %>
  <i class="far fa-calendar-plus fa-lg"></i>
  <% end %>
  <p>Create</p>
  </div>

<!-- camera -->
  <div class="center">
  <%= link_to camera_path, class: "navbar-camera" do %>
  <i class="fas fa-camera fa-lg"></i>
  <% end %>
  <p>Camera</p>
  </div>

  <!-- search -->
  <div class="center">
  <%= link_to   search_events_path, class: "search" do %>
  <i class="fas fa-search-location fa-lg"></i>
  <% end %>
  <p>Search</p>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="hidden-md hidden-lg">

    <div class="btn-group dropup center">
      <a href="#" data-toggle="dropdown"><i class="fas fa-user-circle fa-lg" ></i></a>
      <p>Settings</p>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <% if current_user %>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
          <% end %></li>
          <% else %>
          <li><%= link_to new_user_session_path, method: :get do %>
            <i class="fas fa-sign-in-alt"></i> <%= t(".sign_in", default: "Sign in") %>
            <% end %></li>
            <% end %>
            <li><%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %></li>
      </ul>
    </div>
  </div>
</div>

  <!-- loggin
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <%= link_to "Logout", destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link", method: :delete %>


    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.photo == nil %>

        <% else %>
        <%= cl_image_tag current_user.photo, height: 300, width: 400, crop: :fill %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>

    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div> -->