config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/camera', to: 'pages#camera'
  resources :photos, only: [:create, :destroy]

  get '/googleApi', to: 'photos#googleApi'



  resources :users, only: [] do
    resources :photos, only: [] do
    resources :comments, only: [:new, :create]
  end
    resources :events, only: [] do
      resources :event_guests, only: [:create]
      resources :likes, only: [:create, :new]
    end
  end

  resources :events do
    collection do
      get 'search', to: 'events#search'
      get 'nearby', to: 'events#nearby'
    end
    resources :photos, only: [:create, :show, :destroy] do
      get '/like', to: 'likes#like'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :comments
  has_many :event_guests
  has_many :photos
  has_many :users, through: :event_guests
  has_many :comments, as: :commentable
  has_many :likes, through: :photos
  has_many :photo_comments, through: :photos, source: :comments

  validates :creator, presence: true
  validates :name, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def background_url
    self.photos.first&.file.to_s
  end

  def event_avatar
    self.photos.first.nil? ? "default_avatar.png" : self.photos.first.file
  end

  def address_short
    self.location.split(',').first
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :nearby, :search]
  skip_after_action :verify_authorized, only: [:nearby, :search]
  def index
    @events = policy_scope(Event)
    if !current_user.nil? && !current_user.active_event_id.nil?
      @active_event = policy_scope(Event).find(current_user.active_event_id)
      @latest_event = policy_scope(Event).find(current_user.events.last.id)
    end
    # policy_scope(Event) .addOtherMethods
  end

  def show
    @event = authorize Event.find(params[:id])
    @eventguest = EventGuest.new
      if current_user.nil?
        redirect_to new_user_session_url
      end
  end

  def new
    @event = current_user.events.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user
    authorize @event
    if @event.save!
      current_user.active_event_id = @event.id
      current_user.events << @event
      redirect_to event_path(@event), notice: "Your event has been successfully added."
    else
      render :new
    end
  end

  def edit
    # authorize @event
  end

  def update
    # authorize @event
  end

  def destroy
    # authorize @event
    @event = Event.find(params[:id])
    authorize @event
    @event.destroy
    redirect_to events_path
  end

  def search
    @acevents = policy_scope(Event).pluck(:name)
    if params[:query].present?
      @events = policy_scope(Event).where("name ILIKE ?", "%#{params[:query]}%")
    end
  end

  def nearby
    @latitude = params[:lat].to_f
    @longitude = params[:lon].to_f
    @accuracy = params[:acc].to_i

    @events = Event.near([@latitude, @longitude], 50)
    @events.each { |event| event.distance = (event.distance * 100).to_i }

    if @events.any?
      respond_to do |format|
        format.json # { render json: @events } <-- will render `app/views/events/nearby.js.erb`
      end
    end
  end
    # else
    #   respond_to do |format|
    #     format.html { redirect_to events_path }
    #     format.js  # <-- idem
    #   end
    # end
  private

  def event_params
    params.require(:event).permit(:name, :location, :radius, :start_date, :end_date, :access_key)
  end
end

app/views/events/_noevent.html.erb
<div class="container whitebox card-border">

  <div class="row">

      <div class="col-xs-10 col-xs-offset-1 icon">
         <h2>There are no photo in your event album, currentely. </h2>
         <h2>Click on Search or Create to start.</h2>
         <%= image_tag 'iconregister.jpeg' %>
      </div>
  </div>

app/views/events/index.html.erb
<% content_for :title, "Shary Pix - All my events" %>
<div class="container fix-padding">
  <div class="wrapper-topbar" style="background-image: linear-gradient(-225deg, rgba(255, 106, 0, 0.8) 10%, rgba(252, 3, 3, 0.69) 65%);">
    <div class="subcontainer-topbar">
      <div class="topbar-name text-center">
        <p>ALL MY EVENTS</p>
      </div>
    </div>
  </div>
  <div class="subcontainer">
    <% if current_user.nil? %>
    <div class="flex-container infobox">
      <div class="no-login-card">
        <div class="no-login info-box">
          <div class="no-login-text">
            <h1>Please Login to see your events</h1>
          </div>
        </div>
      </div>
      <div class="actions">
        <div class="login">
          <%= link_to "LOGIN", new_user_session_path, class: "btn-shary login" %>
        </div>
      </div>
    </div>
    <% elsif current_user.active_event_id.nil? || @latest_event.nil? %>
    <div class="flex-container infoboxno">
      <div class="no-login-card">
        <div class="no-login info-box">
          <div class="no-login-text">
            <%= render 'events/noevent' %>
          </div>
        </div>
      </div>
    </div>
    <% else %>
    <%= link_to event_path(@active_event) do %>
    <div class="latest-event card-border">
      <% if @active_event.photos.first.present? %>
      <%= cl_image_tag(@active_event.photos.first.file) %>
      <% end %>
      <div class="latest-event-infos">
        <div id="up">Up!</div>
        <% if @active_event.creator.photo.present? %>
        <%= cl_image_tag(@active_event.creator.photo, class: "avatar-small") %>
        <% end %>
        <div class="lastest-event-details">
          <p class="card-event-name"><%= @active_event.name %></p>
          <p class="card-event-location"><%= @active_event.location %></p>
        </div>
      </div>
    </div>
    <% end %>
<!--     <% if current_user.active_event_id != current_user.events.last.id %>
    <h4 class="events-block-title">Your latest event</h4>
    <%= link_to event_path(@latest_event) do %>
    <div class="latest-event card-border">
      <% if @latest_event.photos.first.present? %>
      <%= cl_image_tag(@latest_event.photos.first.file) %>
      <% end %>
      <div class="latest-event-infos">
        <%= cl_image_tag(@latest_event.creator.photo, class: "avatar-small") %>
        <div class="lastest-event-details">
          <p class="lastest-event-name"><%= @latest_event.name %></p>
          <p class="lastest-event-location"><%= @latest_event.location %></p>
        </div>
      </div>
    </div>
    <% end %>
    <% end %> -->
    <p class="events-block-title">All my events</p>
    <div class="all-events">
      <% current_user.events.reverse_each do |event| %>
      <% if event.photos.first.present? %>
      <%= link_to event_path(event) do %>
      <div class="event-small-card card-border">
        <%= cl_image_tag(event.photos.first.file) %>
        <div class="event-small-card-infos">
          <p class="card-event-name small-title"><%= event.name %></p>
          <p class="card-event-location"><%= event.location %></p>
          <p class="card-event-date">started: <%= event.start_date %></p>
          <div class="card-event-created-by">
            <% if @active_event.creator.photo.present? %>
              <%= cl_image_tag(event.creator.photo, class: "avatar-small") %>
            <% end %>
            <div>
              <p>created by</p>
              <p><%= event.creator.name %></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<% content_for :title, "Shary Pix - Create a new event to share photos" %>
<div class="wrapper-topbar" style="background-image: linear-gradient(-225deg, rgba(255, 106, 0, 0.8) 10%, rgba(252, 3, 3, 0.69) 65%);">
  <div class="subcontainer-topbar">
      <div class="topbar-name text-center">
        <p>CREATE A NEW EVENT</p>
      </div>
  </div>
</div>
<div class="subcontainer">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4">
      <%= simple_form_for @event do |f| %>
        <div class="form-inputs">
          <%= f.input :name, required: false, autofocus: true , placeholder: "Write the name of your event" %>
          <%= f.input :location, required: false, autofocus: true , placeholder: "Where does your event take place ?"  %>
          <%= f.input :start_date, as: :string %>
          <%= f.input :end_date, as: :string %>
           <div class = "checkbox">
          <%= f.input :public, as: :boolean, label: "Private event" %>
          </div>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Create a new event", class: "btn-shary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/search.html.erb
<% content_for :title, "Shary Pix - Search for new events around your location or by name!" %>
<div class="wrapper-topbar" style="background-image: linear-gradient(-225deg, rgba(255, 106, 0, 0.8) 10%, rgba(252, 3, 3, 0.69) 65%);">
  <div class="subcontainer-topbar">
    <div class="topbar-name text-center">
      <p>SEARCH FOR NEW EVENTS</p>
    </div>
  </div>
</div>
<div class="subcontainer">
  <div class="searches">
    <div class="search-by-name">
      <%= form_tag search_events_path, method: :get, class: "form-inline" do %>
        <div id= "search-data" class="form-search search-data" data-acevents="<%= @acevents.to_json %>">
          <%= text_field_tag :query, params[:query], autocomplete: :off, class: "form-control search-input", placeholder: "Search by name" %>
          <div id= "search-data" class="form-search search-data" data-acevents="<%= @acevents.to_json %>">
          </div>
        </div>
      <% end %>
    </div>
    <p class="text-center" style="margin: 10px;">or</p>
    <div class="by-location">
      <p class="btn-shary" id="search-by-location">Search near your current location</p>
    </div>
  </div>
  <div id="events-nearby">
    <% if @events.present? %>
      <% @events.each do |event| %>
        <%= link_to event_path(event) do %>
                <div class='result'>
                  <div class="event-creator-avatar">
                    <%= image_tag(event.creator.user_avatar, :style=>'height:40px; width:40px; border-radius:50px;') %>
                  </div>
                  <div class="result-central">
                    <div class="event-name"><%= event.name %></div>
                    <div class="event-location-results"><%= event.location %></div>
                  </div>
                </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% content_for :title, "Shary Pix - Event: #{@event.name}" %>
<div class="wrapper-header" style="background-image: linear-gradient(-225deg, rgba(255, 106, 0, 0.8) 10%, rgba(252, 3, 3, 0.69) 65%), url(<%= @event.background_url %>);">
  <div class="subcontainer-header">
    <div class="event-header">
      <% if policy(@event).destroy? %>
        <div class="destroy-event">
          <p>
            <%= link_to event_path(@event), method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </p>
        </div>
      <% end %>
      <div class="event-header-top text-center">
        <p id="event-name"><%= @event.name.upcase %></p>
        <p id="event-location-short"><%= @event.location %></p>
      </div>
      <div class="event-header-bottom">
        <div class="event-header-bottom-left">
          <div class="stats" id="photos">
            <p class="stat-number"><%= @event.photos.count %></p>
            <p class="stat-category"><%= pluralize(@event.photos.count, 'photo').split(' ').last.upcase %></p>
          </div>
          <div class="stats" id="likes">
            <p class="stat-number"><%= @event.likes.count %></p>
            <p class="stat-category"><%= pluralize(@event.likes.count, 'like').split(' ').last.upcase %></p>
          </div>
        </div>
        <div class="event-header-avatar">
          <%= image_tag(@event.event_avatar) %>
        </div>
        <div class="event-header-bottom-right">
          <div class="stats" id="members">
            <p class="stat-number"><%= @event.users.count %></p>
            <p class="stat-category"><%= pluralize(@event.users.count, 'member').split(' ').last.upcase %></p>
          </div>
          <div class="stats" id="comments">
            <p class="stat-number"><%= @event.photo_comments.count %></p>
            <p class="stat-category"><%= pluralize(@event.photo_comments.count, 'comment').split(' ').last.upcase %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="subcontainer-gallery">
  <% if current_user.is_not_guest?(@event) %>
    <div class= "text-center btn-event-show">
      <%= simple_form_for [@eventguest], url: user_event_event_guests_path(current_user, @event), :method => :post do |f| %>
      <%= f.submit "Join to see all photos", class: "btn-shary" %>
      <% end %>
    </div>
  <% elsif current_user.active_event_id != @event.id  %>
    <div class="text-center btn-event-show">
      <%= simple_form_for [@eventguest], url: user_event_event_guests_path(current_user, @event), :method => :post do |f| %>
        <%= f.submit "Participate", class: "btn-shary" %>
      <% end %>
    </div>
    <div class="gallery">
      <div class="row">
        <% @event.photos.each do |photo| %>
          <%= link_to event_photo_path(@event, photo) do %>
            <div class="col-xs-6 col-md-4">
              <div class="photo">
                <%= cl_image_tag(photo.file) %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="gallery">
      <div class="row">
        <% @event.photos.each do |photo| %>
          <%= link_to event_photo_path(@event, photo) do %>
            <div class="col-xs-6 col-md-4">
              <div class="photo">
                <%= cl_image_tag(photo.file) %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>