config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/camera', to: 'pages#camera'
  resources :photos, only: [:create, :destroy]

  get '/googleApi', to: 'photos#googleApi'



  resources :users, only: [] do
    resources :photos, only: [] do
    resources :comments, only: [:new, :create]
  end
    resources :events, only: [] do
      resources :event_guests, only: [:create]
      resources :likes, only: [:create, :new]
    end
  end

  resources :events do
    collection do
      get 'search', to: 'events#search'
      get 'nearby', to: 'events#nearby'
    end
    resources :photos, only: [:create, :show, :destroy] do
      get '/like', to: 'likes#like'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  #require "google/cloud/vision"
  belongs_to :event
  belongs_to :user
  has_many :photo_tags
  has_many :tags, through: :photo_tags
  has_many :comments, as: :commentable
  has_many :likes

  validates :file, :event, presence: true

  #after_create :add_google_tags

  private

  def add_google_tags
    image_annotator = Google::Cloud::Vision::ImageAnnotator.new(credentials: GOOGLE_APPLICATION_CREDENTIALS)
    response = image_annotator.label_detection(image: file)
    response.responses.each do |res|
      res.label_annotations.each do |label|
        in_tabel = Tag.find_by(name: label.description)
        if in_tabel.nil?
          @tag = Tag.new
          @tag.name = label.description
          @tag.save
        end
        tag = Tag.find_by(name: label.description)
        @photo_tag = PhotoTag.create(
          tag: tag,
          photo: self
        )
      end
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # skip_before_action :authenticate_user!

  skip_before_action :authenticate_user!
  skip_after_action :verify_authorized, only: :googleApi

  def show
    @event = authorize Event.find(params[:event_id])
    @photo = authorize Photo.find(params[:id])
    @comment = Comment.new
  end

  def new
  end

  def create
    @photo = Photo.new(photo_params)
    authorize @photo
    @photo.user = current_user
    @photo.event = Event.find(current_user.active_event_id)
    if @photo.save!
      render json: { event_id: @photo.event_id }
    else
      render :new
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    authorize @photo
    @photo.destroy

    redirect_to @photo.event
  end

  private

  def photo_params
    params.require(:photo).permit(:file)
  end
end

app/views/photos/_comment.html.erb
<%= simple_form_for [@comment], remote: true, url: user_photo_comments_path(current_user, @photo), method: :post, id: :new_comment do |form| %>
  <%= form.input :content, label: false %>
  <%= form.button :submit, class: "create-comment-btn", class: "btn-shary" %>
<% end %>

app/views/photos/googleApi.html.erb
<h1>hello Google Machine Learning </h1>
<ul>
<% @array.each do |label| %>
  <li><%= label %></li>
<% end %>
</ul>

app/views/photos/new.html.erb
<a href="#" id="upload_widget_opener">Upload multiple images</a>

<!--Step 1: Replace the script URL-->
<!--<script src="https://widget.cloudinary.com/global/all.js" type="text/javascript"></script>  -->
<script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript"></script>

app/views/photos/show.html.erb
<% content_for :title, "Shary Pix - Event: #{@event.name} - Photo by #{@photo.user.username}" %>
<div class="container fix-padding">
  <div class="wrapper-topbar" style="background-image: linear-gradient(-225deg, rgba(255, 106, 0, 0.8) 10%, rgba(252, 3, 3, 0.69) 65%);">
    <div class="subcontainer-topbar">
      <div class="back-arrow text-center">
        <%= link_to event_path(@event) do %>
          <p><i class="fas fa-chevron-left"></i></p>
        <% end %>
      </div>
      <div class="topbar-name text-center" id="photo-show-title">
        <p><%= @event.name.upcase %></p>
      </div>
    </div>
  </div>
  <div class="subcontainer">
    <div class="posted-by">
      <div class="publisher-avatar">
        <%= image_tag(@photo.user.user_avatar, :style=>'height:40px; width:40px; border-radius:50px;') %>
      </div>
      <div class="publishing-name">
        <p> posted by <%= @photo.user.name %></p>
      </div>
    </div>
    <div class="photo-card card-border">
      <div class="photo-image">
        <%= cl_image_tag(@photo.file, class: "main-image")%>
      </div>
      <div class="photo-info">
        <div class="likes">
          <%= link_to event_photo_like_path(@photo.event, @photo) do %>
            <% if current_user.is_liking?(@photo) %>
              <p><i class="fas fa-heart" style="color: rgba(252, 3, 3, 0.69);"></i> <%= @photo.likes.count %></p>
            <% else %>
              <p><i class="far fa-heart"></i> <%= @photo.likes.count %></p>
            <% end %>
          <% end %>
        </div>
        <div class="comments">
          <p><i class="far fa-comment"></i> <%= @photo.comments.count %></p>
        </div>
        <% if policy(@photo).destroy? %>
          <div class="destroy">
            <p>
              <%= link_to photo_path(@photo), method: :delete do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </p>

          </div>
         <% end %>
      </div>
    </div>
<!--     <div class="section">
      <p class="section-title">Tags</p>
      <% @photo.photo_tags.each do |tag| %>
        <p class="tag">#<%= tag.tag.name %></p>
      <% end %>
    </div> -->
    <div class="section">
      <p class="section-title">Comments</p>
      <%= render 'photos/comment', photo: @photo, comment: @comment %>
      <div id="comments">
        <% @photo.comments.each do |comment| %>
            <%= render 'comments/show', comment: comment %>
        <% end %>
      </div>
    </div>
  </div>
</div>